### ISSUE TITLE
Restrict auto update to the installed version

### ISSUE THREAD

**Issue by lhvy** [Owen-Cochell/PaperMC-Update#10]
Is there a way to configure this tool to only update to the latest build of the current server version? (i.e., downloading the latest 1.18.1 build instead of downloading a 1.18.2 build)

**Comment by Owen-Cochell** [comment]
Yes! You can do this like so:

python server_update.py -v [VERSION] [PATH]

Where [VERSION] is the version you wish to stay on, and [PATH] is the path to your paper jar file. Using your example, the command will look like this:

python server_update.py -v 1.18.1 [PATH]

This will ensure that any version changes are ignored, and that the server should only be updated if there is a new build for your specified version. If this is not what you are looking for, then let me know and we can figure something out.

**Comment by lhvy** [comment]
Sorry, what I meant was is it possible to auto detect the current version and set that as the version flag? (So if I change the version of Paper, the server update command wouldn't need changing and would just keep builds for that version up to date)

**Comment by lhvy** [comment]
I've had an attempt at what I was describing in a fork here [fb2270e](https://github.com/lhvy/PaperMC-Update/commit/fb2270eba337b895b7a57fcc38f50a81530ce1e8). How does this look? I can make a PR if you think this is a useful addition.

**Comment by lhvy** [comment]
Sorry for the delay, this looks perfect thanks!

My only comment is that the following line in the readme about using the `current` keyword for the build might not be correct.

> You can also use these keywords for selecting the build, although using the current keyword for build selection is not recommended!

(I read through the changes in 1ca4a89, and I'm not sure if the `current` keyword is actually implemented for the build number.)

**Comment by Owen-Cochell** [comment]
You are 100% correct. If the `current` keyword is encountered, it will always resolve to the currently installed version. This will become a problem if a user uses it to select a build. You can find this implementation in the `_select()` method in the `ServerUpdater` class. This method is used to interpret keywords and ensure that the selected value is valid. I have a fix for this problem, and I will be pushing it out hopefully soon.

Thanks again for pointing this out! Hopefully this new release will solve this issue once and for all.

**Comment by lhvy** [comment]
Seems like the fix was applied in the latest commit. Thanks for the quick responses and implementing this feature, it is very helpful for my server! :)
