### ISSUE TITLE
Feature request: View changelogs before applying

### ISSUE THREAD

**Issue by Darkhand81** [Owen-Cochell/PaperMC-Update#11]
Hi!

First off, I love this script!  I was browsing the Paper download API documentation and getting ready to start my own much simpler downloader when I thought that someone must have already done this, and I found you.  Lightyears better than I could have done!

One of the things I do religiously before updating is check the changelogs of each build before updating the server.  Would it be possible to display all the changelog summaries from the API data of each build in interactive mode, when it's listing out all the build numbers to choose from? 

Example output from interactive mode:

```
Please enter the build you would like to download:
Example: 205
(Tip: The value enclosed in brackets is the default option. Leave the prompt blank to accept it.)
(Tip: Enter 'latest' to select the latest build.)

Available Builds:
  > Build Num: [229] - 2022-03-06 - Fix save problems on shutdown
  > Build Num: [230] - 2022-03-06 - Add more to the save fixes
  > Build Num: [231] - 2022-03-06 - Updated Upstream (CraftBukkit)
  > Build Num: [232] - 2022-03-06 - Fix scoreboard objective name length limit
  > Build Num: [233] - 2022-03-06 - Add method to set noclip on arrows (#7263)
  > Build Num: [234] - 2022-03-06 - Add ghast api (#7554)
...
```

That would save a ton of time vs having to crack open a browser and check manually, especially for folks like me who are managing through SSH.

Thanks again for such a cool script!

**Comment by Owen-Cochell** [comment]
Hello, and thank you so much for the support! Really does mean a lot.

I think this is an amazing feature, most of the functionality for this is present, so I think adding it would be pretty simple. I will do some experimenting to see how this can get fit in. We already have support for displaying statistics on builds, but it is not implemented in the interactive menu. The only issue I can see as of now is that we may have to make a bunch of calls to the API to retrieve stats for each and every build/version. I would like to avoid flooding the API if possible, but I will do some experimentation.

In the meantime, you can view build change logs and other stats from the terminal using this script. It may not be as graceful as embedding the stats in the interactive menu, but it works nonetheless! You can do this like so:

`python server_update.py --stats -c -nc -i [PATH]`

Where [PATH] is the path to your jar file. The `-c` and `-nc` prevents the script from messing with your current install, and can be omitted if necessary. The important flag here is the `--stats` flag, which prints out all available stats on the selected build. This command will prompt you for a version and build as usual. After you have made your selection, the stats will be displayed. You can also do this non-interactively by using the `-v` and `-b` flags to select your version and build.

Thanks again for the support! I will be looking into this to see if embedding statistics into the interactive menu is achievable without an unreasonable amount of API requests.

**Comment by Owen-Cochell** [comment]
Hello! After doing some more research, I unfortunately can't in good faith display commit stats on the interactive menu for every build. Making a call to the API for each build number would mean that we may make hundreds of requests at a time. I do not think it is a good idea to put this much strain on the API.

I think the current solution, the `--stats` method, is what you are looking for. If this is the case, then please feel free to close this issue. However, if this solution is not what you are looking for, then please let me know and we can figure something out! Thanks again for pointing this out, please let me know if you need something more.

**Comment by Darkhand81** [comment]
Understandable! Thanks for looking into it though.  I'll make a request to the Paper devs to see if they can update the API to include a consolidated changelog, perhaps per Minecraft version... It would benefit them and decrease load on their API after all.

If there's a good response I'll let you know!

Thanks again!

**Comment by Owen-Cochell** [comment]
I suppose so, that is a good point. Users will likely not see a major performance hit, and the API will likely be just fine. However, I like to be respectful when talking to APIs, and the functionality for getting info on a specific version is already there with the 
`--stats` argument. It may not be as convenient, but it is possible to get changelog stuff without this script touching your install. Plus, most users will only be interested in checking a specific version at a time, and will likely ignore the potentially hundreds of other change logs that are displayed in the interactive menu. 

There are valid points for both, but I think that the utility of seeing a change log for each build in the interactive menu does not outweigh spamming the API. I could be wrong though, this feature may not be as niche as I think lol

**Comment by NoahvdAa** [comment]
Sounds like you can get the data you're looking for with the [version family builds endpoint](https://api.papermc.io/docs/swagger-ui/index.html?configUrl=/openapi/swagger-config#/version-family-builds-controller/familyBuilds) or the '[newly added](https://github.com/PaperMC/bibliothek/commit/f38f98c87d6ccec0d7a26cffa21ce7f56bc84e07)' (after this issue was created at least) [version builds endpoint](https://api.papermc.io/docs/swagger-ui/index.html?configUrl=/openapi/swagger-config#/version-builds-controller/builds).
