### ISSUE TITLE
"from __future__ import annotations" error I am getting.

### ISSUE THREAD

**Issue by Epicjii** [Owen-Cochell/PaperMC-Update#12]
"syntaxerror: future feature annotations is not defined" is the error I am getting

I am using Linux mint with python 3.6 installed as well

**Comment by Owen-Cochell** [comment]
Thank you for pointing this out! The readme does say that you need at least Python 3.6, which is incorrect in this case. I'll bump that up to Python 3.7. If you have any other issues or questions please let me know.

**Comment by Owen-Cochell** [comment]
The lowest version has been updated in both the readme and the script. The script will now exit if you are attempting to run with a version of Python lower than 3.7. The version you want is 2.2.1. If this solves your problem them please feel free to close this issue.

Thanks!
