### ISSUE TITLE
Tips for running on Debian 10 

### ISSUE THREAD

**Issue by OskyEdz** [Owen-Cochell/PaperMC-Update#6]
I've never used Python on Debian before so I din't understand why the program didn't run at first.
I spent half an hour reinstalling python3 on my system.
I use Debian 10 and I had both python2 and python3 installed. 
So when I ran python server_update.py [PATH] I got a traceback error:

`Traceback (most recent call last):
  File "server_update.py", line 2, in <module>
    import urllib.request
ImportError: No module named request
`

To avoid this I had to run  **python3** server_update.py [PATH]

To make an suggestion; either mention "python3" in the README.md or add version check at the start of the program.

**Comment by Owen-Cochell** [comment]
That's a good catch. Running the correct version of python can get tricky with multiple versions installed.

I will add this information to the readme. I will also add a version check in the code that will make this clear to the user that it requires python 3.6 or above. I'll get this out in the next few hours.

Thanks for the feedback and apologies for any confusion!

**Comment by Owen-Cochell** [comment]
Alright, pushed out a check at the start of the code, and added a section in the readme about python versions and how to check them and select them.

When you get a chance, I would appreciate it if you tested the script with the 'python3' and 'python' command. You should get a message for 'python' about incorrect versions, and 'python3' should work fine. If this this the case and the solution is to your liking, then I will close this issue.

Thanks!

**Comment by Owen-Cochell** [comment]
Closed due to inactivity
