### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'script_version'

### ISSUE THREAD

**Issue by jlg89** [Owen-Cochell/PaperMC-Update#7]
Just installed server_update.py and I'm getting an odd error. I reckon I'm doing something wrong, but I dunno what.

<pre>
# /opt/local/bin/python3.8 server_update.py -V
1.2.1

# /opt/local/bin/python3.8 server_update.py --check-only ./
+==========================================================================+
|     _____                              __  __          __      __        |
|    / ___/___  ______   _____  _____   / / / /___  ____/ /___ _/ /____    |
|    \__ \/ _ \/ ___/ | / / _ \/ ___/  / / / / __ \/ __  / __ `/ __/ _ \   |
|   ___/ /  __/ /   | |/ /  __/ /     / /_/ / /_/ / /_/ / /_/ / /_/  __/   |
|  /____/\___/_/    |___/\___/_/      \____/ .___/\__,_/\__,_/\__/\___/    |
|                                         /_/                              |
+==========================================================================+

[PaperMC Server Updater]
[Handles the checking, downloading, and installation of server versions]
[Written by: Owen Cochell]

Traceback (most recent call last):
  File "server_update.py", line 1126, in <module>
    if args.script_version:
AttributeError: 'Namespace' object has no attribute 'script_version'
</pre>

**Comment by Owen-Cochell** [comment]
Thanks for the input. You were using the script correctly, the issue is a bug.

When I added the option for argparse to handle the version parameter, I forgot to remove a chunk of code that referenced the old attribute for script version, thus causing this error.

I'll get a fix for this in the next few minutes, as this is a big deal. Thanks for reporting this!

**Comment by Owen-Cochell** [comment]
Alright, this should fix it. Apologies for the delay, something came up.

If the issue is resolved on your end then I will close this issue.

**Comment by jlg89** [comment]
That fixed it. Works great!
